debug: true

spring:
  h2:
    console:
      enabled: true
  datasource:
    name: petowner
    username: petowner
    password: petowner
    url: jdbc:h2:mem:petowner;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;
